packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - vue-demi
